server:
  port: 10086
spring:
  application:
    name: eureka_service_10086
eureka:
  instance:
    hostname: eureka10086.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka10087.com:10087/eureka/