server:
  port: 3344
spring:
  application:
    name: could-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yangpengpeng1/springcloud-config.git
          #搜索目录
          search-paths: springcloud-config
      #读取分支
      label: master
    #配置rabbitmq
  rabbitmq:
    host: 192.168.128.130
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/,http://eureka10087.com:10087/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
#rabbitmq相关配置 暴露bus refresh端点