server:
  port: 8005
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/,http://eureka10087.com:10087/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: hystrixPayment8005