server:
  port: 80
spring:
  application:
    name: cloud-hystrix-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka10086.com:10086/eureka/,http://eureka10087.com:10087/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
feign:
  hystrix:
    enabled: true